# Jekyll Defaults
title: ECCI
description: Edinburgh Computational Cardiovascular Imaging research group website.
baseurl: ""

url: "https://ecci-cvs.github.io"
github: http://github.com/ecci-cvs/ecci-svs.github.io
highlighter: rouge
markdown: kramdown
permalink: /post/:title/

collections:
  research:
    output: true

gems: [jekyll-paginate]
plugins:
  [jekyll-paginate]
paginate: 4
paginate_path: "/research/page:num"

rss_path: /feed.xml
navigation:
- text: The Team
  url: /team/
- text: Jobs
  url: /jobs/
- text: Datasets
  url: /datasets/
- text: Software
  url: /software/
- text: Research
  url: /research/
- text: Contact Us
  url: /contact/
